/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.ivyft.katta.yarn.protocol;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum IdType { 
  CONTAINER_ID, NODE_ID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"IdType\",\"namespace\":\"com.ivyft.katta.yarn.protocol\",\"symbols\":[\"CONTAINER_ID\",\"NODE_ID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
