/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.ivyft.katta.yarn.protocol;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum NodeType { 
  KATTA_MASTER, KATTA_NODE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NodeType\",\"namespace\":\"com.ivyft.katta.yarn.protocol\",\"symbols\":[\"KATTA_MASTER\",\"KATTA_NODE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
