/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.ivyft.katta.protocol;

@SuppressWarnings("all")
/** Hello */
@org.apache.avro.specific.AvroGenerated
public interface KattaClientProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"KattaClientProtocol\",\"namespace\":\"com.ivyft.katta.protocol\",\"doc\":\"Hello\",\"types\":[{\"type\":\"record\",\"name\":\"Message\",\"doc\":\"传输的 Avro 消息, 序列化结果\",\"fields\":[{\"name\":\"indexId\",\"type\":\"string\",\"doc\":\"Index ID\"},{\"name\":\"rowId\",\"type\":\"string\",\"doc\":\"Data Shard Key\"},{\"name\":\"payload\",\"type\":\"bytes\",\"doc\":\"Data Bytes\"}]}],\"messages\":{\"add\":{\"doc\":\"插入单条数据\",\"request\":[{\"name\":\"message\",\"type\":\"Message\"}],\"response\":\"int\"},\"addList\":{\"doc\":\"批次插入(List)\",\"request\":[{\"name\":\"messages\",\"type\":{\"type\":\"array\",\"items\":\"Message\"}}],\"response\":\"int\"},\"comm\":{\"doc\":\"提交\",\"request\":[{\"name\":\"indexId\",\"type\":\"string\"}],\"response\":\"string\"},\"fsh\":{\"doc\":\"提交成功, 启动创建索引进程\",\"request\":[{\"name\":\"indexId\",\"type\":\"string\"},{\"name\":\"commitId\",\"type\":\"string\"},{\"name\":\"timeout\",\"type\":\"long\"}],\"response\":\"null\"},\"roll\":{\"doc\":\"提交失败回滚\",\"request\":[{\"name\":\"indexId\",\"type\":\"string\"},{\"name\":\"commitId\",\"type\":\"string\"}],\"response\":\"null\"}}}");
  /** 插入单条数据 */
  int add(com.ivyft.katta.protocol.Message message) throws org.apache.avro.AvroRemoteException;
  /** 批次插入(List) */
  int addList(java.util.List<com.ivyft.katta.protocol.Message> messages) throws org.apache.avro.AvroRemoteException;
  /** 提交 */
  java.lang.CharSequence comm(java.lang.CharSequence indexId) throws org.apache.avro.AvroRemoteException;
  /** 提交成功, 启动创建索引进程 */
  java.lang.Void fsh(java.lang.CharSequence indexId, java.lang.CharSequence commitId, long timeout) throws org.apache.avro.AvroRemoteException;
  /** 提交失败回滚 */
  java.lang.Void roll(java.lang.CharSequence indexId, java.lang.CharSequence commitId) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** Hello */
  public interface Callback extends KattaClientProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.ivyft.katta.protocol.KattaClientProtocol.PROTOCOL;
    /** 插入单条数据 */
    void add(com.ivyft.katta.protocol.Message message, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    /** 批次插入(List) */
    void addList(java.util.List<com.ivyft.katta.protocol.Message> messages, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    /** 提交 */
    void comm(java.lang.CharSequence indexId, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    /** 提交成功, 启动创建索引进程 */
    void fsh(java.lang.CharSequence indexId, java.lang.CharSequence commitId, long timeout, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    /** 提交失败回滚 */
    void roll(java.lang.CharSequence indexId, java.lang.CharSequence commitId, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}