/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.ivyft.katta.protocol;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Message extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Message\",\"namespace\":\"com.ivyft.katta.protocol\",\"fields\":[{\"name\":\"indexId\",\"type\":\"string\"},{\"name\":\"rowId\",\"type\":\"string\"},{\"name\":\"payload\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence indexId;
  @Deprecated public java.lang.CharSequence rowId;
  @Deprecated public java.nio.ByteBuffer payload;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Message() {}

  /**
   * All-args constructor.
   */
  public Message(java.lang.CharSequence indexId, java.lang.CharSequence rowId, java.nio.ByteBuffer payload) {
    this.indexId = indexId;
    this.rowId = rowId;
    this.payload = payload;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return indexId;
    case 1: return rowId;
    case 2: return payload;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: indexId = (java.lang.CharSequence)value$; break;
    case 1: rowId = (java.lang.CharSequence)value$; break;
    case 2: payload = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'indexId' field.
   */
  public java.lang.CharSequence getIndexId() {
    return indexId;
  }

  /**
   * Sets the value of the 'indexId' field.
   * @param value the value to set.
   */
  public void setIndexId(java.lang.CharSequence value) {
    this.indexId = value;
  }

  /**
   * Gets the value of the 'rowId' field.
   */
  public java.lang.CharSequence getRowId() {
    return rowId;
  }

  /**
   * Sets the value of the 'rowId' field.
   * @param value the value to set.
   */
  public void setRowId(java.lang.CharSequence value) {
    this.rowId = value;
  }

  /**
   * Gets the value of the 'payload' field.
   */
  public java.nio.ByteBuffer getPayload() {
    return payload;
  }

  /**
   * Sets the value of the 'payload' field.
   * @param value the value to set.
   */
  public void setPayload(java.nio.ByteBuffer value) {
    this.payload = value;
  }

  /** Creates a new Message RecordBuilder */
  public static com.ivyft.katta.protocol.Message.Builder newBuilder() {
    return new com.ivyft.katta.protocol.Message.Builder();
  }
  
  /** Creates a new Message RecordBuilder by copying an existing Builder */
  public static com.ivyft.katta.protocol.Message.Builder newBuilder(com.ivyft.katta.protocol.Message.Builder other) {
    return new com.ivyft.katta.protocol.Message.Builder(other);
  }
  
  /** Creates a new Message RecordBuilder by copying an existing Message instance */
  public static com.ivyft.katta.protocol.Message.Builder newBuilder(com.ivyft.katta.protocol.Message other) {
    return new com.ivyft.katta.protocol.Message.Builder(other);
  }
  
  /**
   * RecordBuilder for Message instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Message>
    implements org.apache.avro.data.RecordBuilder<Message> {

    private java.lang.CharSequence indexId;
    private java.lang.CharSequence rowId;
    private java.nio.ByteBuffer payload;

    /** Creates a new Builder */
    private Builder() {
      super(com.ivyft.katta.protocol.Message.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.ivyft.katta.protocol.Message.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.indexId)) {
        this.indexId = data().deepCopy(fields()[0].schema(), other.indexId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.rowId)) {
        this.rowId = data().deepCopy(fields()[1].schema(), other.rowId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.payload)) {
        this.payload = data().deepCopy(fields()[2].schema(), other.payload);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Message instance */
    private Builder(com.ivyft.katta.protocol.Message other) {
            super(com.ivyft.katta.protocol.Message.SCHEMA$);
      if (isValidValue(fields()[0], other.indexId)) {
        this.indexId = data().deepCopy(fields()[0].schema(), other.indexId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.rowId)) {
        this.rowId = data().deepCopy(fields()[1].schema(), other.rowId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.payload)) {
        this.payload = data().deepCopy(fields()[2].schema(), other.payload);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'indexId' field */
    public java.lang.CharSequence getIndexId() {
      return indexId;
    }
    
    /** Sets the value of the 'indexId' field */
    public com.ivyft.katta.protocol.Message.Builder setIndexId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.indexId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'indexId' field has been set */
    public boolean hasIndexId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'indexId' field */
    public com.ivyft.katta.protocol.Message.Builder clearIndexId() {
      indexId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'rowId' field */
    public java.lang.CharSequence getRowId() {
      return rowId;
    }
    
    /** Sets the value of the 'rowId' field */
    public com.ivyft.katta.protocol.Message.Builder setRowId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.rowId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'rowId' field has been set */
    public boolean hasRowId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'rowId' field */
    public com.ivyft.katta.protocol.Message.Builder clearRowId() {
      rowId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'payload' field */
    public java.nio.ByteBuffer getPayload() {
      return payload;
    }
    
    /** Sets the value of the 'payload' field */
    public com.ivyft.katta.protocol.Message.Builder setPayload(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.payload = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'payload' field has been set */
    public boolean hasPayload() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'payload' field */
    public com.ivyft.katta.protocol.Message.Builder clearPayload() {
      payload = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Message build() {
      try {
        Message record = new Message();
        record.indexId = fieldSetFlags()[0] ? this.indexId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.rowId = fieldSetFlags()[1] ? this.rowId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.payload = fieldSetFlags()[2] ? this.payload : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
